// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddAssetTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void AddAsset()
    {
        // Test name: AddAsset
        // Step # | name | target | value
        // 1 | open | /config/assets | 
        driver.Navigate().GoToUrl("https://retailrui.azurewebsites.net/config/assets");
        // 2 | setWindowSize | 1440x900 | 
        driver.Manage().Window.Size = new System.Drawing.Size(1440, 900);
        // 3 | click | linkText=Add | 
        driver.FindElement(By.LinkText("Add")).Click();
        // 4 | click | css=.form-group:nth-child(1) > .form-control | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .form-control")).Click();
        // 5 | type | css=.form-group:nth-child(1) > .form-control | K001
        driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .form-control")).SendKeys("K001");
        // 6 | click | css=.form-group:nth-child(2) > .form-control | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(2) > .form-control")).Click();
        // 7 | type | css=.form-group:nth-child(2) > .form-control | Computer
        driver.FindElement(By.CssSelector(".form-group:nth-child(2) > .form-control")).SendKeys("Computer");
        // 8 | click | css=.form-group:nth-child(3) > .form-control | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(3) > .form-control")).Click();
        // 9 | type | css=.form-group:nth-child(3) > .form-control | 500
        driver.FindElement(By.CssSelector(".form-group:nth-child(3) > .form-control")).SendKeys("500");
        // 10 | click | css=.form-group:nth-child(4) > .form-control | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(4) > .form-control")).Click();
        // 11 | type | css=.form-group:nth-child(4) > .form-control | PNK9000
        driver.FindElement(By.CssSelector(".form-group:nth-child(4) > .form-control")).SendKeys("PNK9000");
        // 12 | click | css=.form-group:nth-child(5) > .form-control | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(5) > .form-control")).Click();
        // 13 | type | css=.form-group:nth-child(5) > .form-control | MAC002
        driver.FindElement(By.CssSelector(".form-group:nth-child(5) > .form-control")).SendKeys("MAC002");
        // 14 | click | css=.form-group:nth-child(6) > .form-control | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(6) > .form-control")).Click();
        // 15 | select | css=.form-group:nth-child(6) > .form-control | label=Type 1
        {
            var dropdown = driver.FindElement(By.CssSelector(".form-group:nth-child(6) > .form-control"));
            dropdown.FindElement(By.XPath("//option[. = 'Type 1']")).Click();
        }
        // 16 | click | css=.form-group:nth-child(6) option | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(6) option")).Click();
        // 17 | click | css=.form-group:nth-child(7) > .form-control | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(7) > .form-control")).Click();
        // 18 | select | css=.form-group:nth-child(7) > .form-control | label=Category 1
        {
            var dropdown = driver.FindElement(By.CssSelector(".form-group:nth-child(7) > .form-control"));
            dropdown.FindElement(By.XPath("//option[. = 'Category 1']")).Click();
        }
        // 19 | click | css=.form-group:nth-child(7) option | 
        driver.FindElement(By.CssSelector(".form-group:nth-child(7) option")).Click();
        // 20 | click | id=IsAssetActive | 
        driver.FindElement(By.Id("IsAssetActive")).Click();
        // 21 | click | css=.form-group > .btn | 
        driver.FindElement(By.CssSelector(".form-group > .btn")).Click();
        // 22 | click | css=.iziToast-title | 
        driver.FindElement(By.CssSelector(".iziToast-title")).Click();
    }
}

